repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        types: [python]
      - id: end-of-file-fixer
        types: [python]
      - id: check-toml
      - id: check-yaml
      - id: pretty-format-json
        args: ["--indent=4", "--autofix", "--no-sort-keys"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
