[workspace]
members = [
    "days/01",
    "days/02",
    "days/03"
]
resolver = "2"

[workspace.package]
authors = ["Carter Himmel"]
edition = "2021"
include = ["src/**/*.rs"]
license = "MIT"
rust-version = "1.65"
