[workspace]
members = [
    "2022/01",
    "2022/02",
    "2022/03",
    "2022/04",
    "2022/05",
    "2022/06"
]
resolver = "2"

[workspace.package]
authors = ["Carter Himmel"]
edition = "2021"
include = ["src/**/*.rs"]
license = "MIT"
rust-version = "1.65"
