#!/usr/bin/env perl

use strict;
use warnings;

my $day = shift @ARGV;
$day = "0$day" if $day < 10 && substr($day, 0, 1) ne '0';

for my $dir (`find 2023 -type d -name "$day*"`) {
    chomp $dir;
    print "running $dir/solve.pl\n";
    my $args = join ' ', @ARGV;
    system("$dir/solve.pl $args");
}
